[build]
  functions = "functions"
  command = "yarn build"
  publish = "dist"

[dev]
  command = "yarn dev"
  autoLaunch = false

[[redirects]]
  force = true
  from = '/api/*'
  to = '/.netlify/functions/:splat'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200